# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install needed packages specified in requirements.txt
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY src/ .

# Make port 8501 for container to communicate with external services
EXPOSE 8501

# Run distributed-training.py when the container launches
CMD ["python", "distributed-training.py"]
