name: Continuous Integration and Deployment

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'pipelines/**'
      - 'KServe/**'
      - 'model_store/**'

jobs:
  pipeline-deployment:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[trigger pipeline]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install kfp

      - name: Deploy Kubeflow Pipeline
        run: python ./pipelines/deployment/deploy_pipeline.py ./pipelines/training/pipeline.py MyPipelineFunction https://<your-kubeflow-host> MyExperiment

  model-deployment:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[trigger model-deployment]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ./kubeconfig
          export KUBECONFIG=./kubeconfig

      - name: Deploy KServe in Development
        if: github.ref == 'refs/heads/dev'
        run: kubectl apply -f KServe/dev/inference-service-ab-testing.yaml

      - name: Deploy KServe in Production
        if: github.ref == 'refs/heads/main'
        run: kubectl apply -f KServe/prod/model_serving.yaml

