apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource-quotas
  namespace: production
spec:
  hard:
    requests.cpu: "20"  # Allows for higher CPU requests to accommodate more intensive applications.
    requests.memory: 32Gi  # Allows for higher memory requests suitable for production workloads.
    limits.cpu: "40"  # Higher CPU limits to cater to critical performance requirements.
    limits.memory: 64Gi  # Higher memory limits to ensure applications can handle increased data processing.
    pods: "500"  # Increased number of pods to support scaling of services as needed.
