apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow-serving
  template:
    metadata:
      labels:
        app: tensorflow-serving
    spec:
      containers:
      - name: serving-container
        image: tensorflow/serving:latest
        ports:
        - containerPort: 8501
        env:
        - name: MODEL_NAME
          value: my_model
        volumeMounts:
        - mountPath: /models/my_model
          name: model-volume
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
